### ISSUE TITLE
Text is not visible anymore when reaching end of screen on iPad

### ISSUE THREAD

**Issue by AntonOellerer** [writefreely/writefreely-swiftui-multiplatform#257]
Hey,
Another issue I found is that sometimes, when writing text reaching the end of the screen, lines below its height are not shown anymore, and cannot be scrolled to anymore.
I am using an iPad 6th generation, iPadOs 17.4

# Steps to reproduce
1. Create new post on iPad
2. Write text until end of screen (in horizontal view)
3. Write another line

# Expected behaviour
View scrolls down a little

# Actual behaviour
View does not scroll down and cannot be scrolled down, thus no way of seeing new text

**Comment by AngeloStavrow** [comment]
@AntonOellerer thanks for sharing this! I'm not able to reproduce this on the latest version of the app (v1.0.17 build 708). Do you think you could attach a screen recording of what you're experiencing? Thanks!

**Comment by AntonOellerer** [comment]
Hey,
I forgot to record the bug when I encountered it, and am now unable too, if I manage to reproduce it I will write you again, sorry
